#!/bin/bash

rm -fr build
mkdir -p build/src

# Copy static resources
cp -r public build

# Copy server sources
cp -r src build
rm -fr build/src/client

# Copy manifests
cp package*json build

# Bundle and minify client JS
npx browserify -g [ babelify --presets [ @babel/preset-env @babel/preset-react ] ] src/client/index.js | npx uglifyjs --compress --mangle > build/public/client.js

# Compile LESS to minified CSS
npx lessc --include-path=public public/client.less | npx cleancss -o build/public/client.css

# Remove LESS source
rm build/public/*.less
