#!/bin/bash

rm -fr build
mkdir -p build/src

# Copy static resources
cp -r public build

# Copy server sources
cp -r src build
rm -fr build/src/client

# Copy manifests
cp package*json build

# Bundle and minify client JS
npx webpack --config webpack.prod.cjs
