- name: create application group
  group:
    name: sataako
    state: present

- name: create application user
  user:
    name: sataako
    group: sataako
    state: present

- name: copy application
  synchronize:
    src: ../build/
    dest: /home/sataako/app
    delete: yes
    recursive: yes
  notify:
   - restart sataako

- name: set file ownership
  file:
    path: /home/sataako/app
    recurse: yes
    owner: sataako
    group: sataako

- name: install node modules
  shell: cd /home/sataako/app && npm ci
  become: yes
  become_user: sataako
  notify:
   - restart sataako

- name: create unit file
  template:
    src: sataako.service.j2
    dest: /etc/systemd/system/sataako.service
    mode: '0644'
  notify:
    - reload systemctl
    - restart sataako

- name: create cache directory
  file:
    path: /var/run/sataako
    state: directory
    owner: sataako
    group: sataako
    mode: '0755'

- name: register cache directory with tmpfiles.d (so that it's recreated on reboot)
  copy:
    src: sataako.conf
    dest: /etc/tmpfiles.d/
    mode: '0644'

- name: enable and starat sataako.fi app
  service:
    name: sataako
    state: started
    enabled: yes
