- name: install nginx, and epel repository (for certbot)
  package:
    name:
      - epel-release
      - nginx
    state: latest

- name: install certbot
  package:
    name:
      - certbot
      - python3-certbot-nginx
    state: latest

- name: create nginx site configuration
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nginx

- name: enable and start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: enable and start certbot renewal timer
  service:
    name: certbot-renew.timer
    state: started
    enabled: yes
